variables:
  image_name: devopshandson3/pyappdemo
  #image_tag: ${CI_COMMIT_SHA:0:3}

stages:
  - Test
  - Build
  - Deploy


run_tests:
    stage: Test
    image: python:3.9-slim
    before_script:
        - apt-get update -y && apt-get install make -y
    script: 
        - make test

Build_and_Push:
  stage: Build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $username -p $token
  script:
    - docker build -t $image_name:${CI_COMMIT_SHA:0:3} .
    - docker push $image_name:${CI_COMMIT_SHA:0:3}

Deploy:
  stage: Deploy
  before_script:
    - echo "Set read permissions to key ..."
    - chmod 400 "$ssh_key"
    - id
  script:
  - ssh -o StrictHostKeyChecking=no -i "$ssh_key" ubuntu@44.202.89.233 "
      sudo apt-get update -y && \
      sudo apt-get install docker.io -y && \
      echo 'Stopping current container ...' && \
      sudo docker ps -q --filter \"publish=5000\" | xargs -r sudo docker stop && \
      echo 'Removing old container ...' && \
      sudo docker ps -aq --filter \"publish=5000\" | xargs -r sudo docker rm && \
      echo 'Running new container ...' && \
      sudo docker run -d -p 5000:5000 --name pyapp $image_name:${CI_COMMIT_SHA:0:3}"





