variables:
  IMAGE_NAME: suman1606/test_docker_repo
  IMAGE_TAG: python-app-1.0
run_tests:
  stage: test
  image: python:3.9-slim-buster
  before_script:
    - apt-get update && apt-get install make
  script:
    - make test

build_image:
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIRS: "/certs"
  before_script:
    - docker login -u $registry_user -P $registry_pass
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG
    - docker push $IMAGE_NAME:$IMAGE_TAG