stages:
  - Test
  - Build
  - Push
  - Deploy


run_tests:
    stage: Test
    image: python:3.9-slim
    before_script:
        - apt-get update -y && apt-get install make -y
    script: 
        - echo "hi" && make --version