variables:
  image_name: devopshandson3/pyappdemo
  image_tag: ${CI_COMMIT_SHA:0:3}

stages:
  - Test
  - Build
  - Deploy


run_tests:
    stage: Test
    image: python:3.9-slim
    before_script:
        - apt-get update -y && apt-get install make -y
    script: 
        - make test

Build_and_Push:
  stage: Build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $username -p $token
  script:
    - docker build -t $image_name:$image_tag .
    - docker push $image_name:$image_tag





