variables:
  IMAGE_NAME: raduraca96/demo-app
  IMAGE_TAG: python-app-1.0

stages:
  - test
  - build

run_tests:
  stage: test
  image: python:3.9-slim
  before_script:
    - apt-get update && apt-get install -y git make
  script:
    - make test

build_image:
  stage: build
  image: docker:28.1.1-cli
  services:
    - docker:28.1.1-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG