variables:
  image_name: devopshandson3/pyappdemo
  #image_tag: ${CI_COMMIT_SHA:0:3}

stages:
  - Test
  - Build
  - Deploy


run_tests:
    stage: Test
    image: python:3.9-slim
    before_script:
        - apt-get update -y && apt-get install make -y
    script: 
        - make test

Build_and_Push:
  stage: Build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $username -p $token
  script:
    - docker build -t $image_name:${CI_COMMIT_SHA:0:3} .
    - docker push $image_name:${CI_COMMIT_SHA:0:3}

Deploy:
  stage: Deploy
  before_script:
    - echo "login to server"
    - ssh -o StrictHostKeyChecking=no -i $ssh_key ubuntu@44.202.89.233
    - apt-get update -y && apt-get install docker.io -y
  script:
    - docker run -d -p 5000:5000 $image_name:${CI_COMMIT_SHA:0:3} --name pyapp





