variables:
  image_name: devopshandson3/pyappdemo
  tag: ${CI_COMMIT_SHA:0:3}

stages:
  - Test
  - Build
  - Deploy


run_tests:
    stage: Test
    image: python:3.9-slim
    before_script:
        - apt-get update -y && apt-get install make -y
    script: 
        - make test

Build_and_Push:
  stage: Build
  image: docker
  before_script:
    - docker login -u $username -p $token
  script:
    - docker build -t $image_name:$tag .
    - docker push $image_name:$tag





