run_tests:
  stage: test
  image: python:3.9-slim-buster
  before_script:
    - apt-get update && apt-get install make
  script:
    - make test

build_image:
  script:
    - docker build -t bakirova/demo:python-app-1.0 .
    - docker push bakirova/demo:python-app-1.0